fixup! exynos9610: switch to common lineage lights hal
Fixes this error when building:
error: hardware/samsung/aidl/light/Android.bp:7:1:
module "android.hardware.light-service.samsung"
variant "android_vendor_arm64_armv8-a":
source path "device/motorola/exynos9610-common/include" does not exist

Change-Id: I6ee0b939004a1ff993e92f1f55133e92f48ca89d